twig:
    default_path: '%kernel.project_dir%/templates'
    # utiliser bootstrap sur tous les formulaires
    # vendor/symfony/twig-bridge/resources/form
    form_themes: [ 'bootstrap_4_layout.html.twig' ]